services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scanner_monitoring
    volumes:
      - .:/var/www
    networks:
      - scanner_monitoring

  nginx:
    image: nginx:alpine
    container_name: scanner_monitoring_nginx
    ports:
      - "1009:1009"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - scanner_monitoring

networks:
  scanner_monitoring:
    driver: bridge
