services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scanner_monitoring
    volumes:
      - .:/var/www
    networks:
      - scanner_monitoring

    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=172.17.0.1
      - DB_PORT=3306
      - DB_DATABASE=scanner_monitoring
      - DB_USERNAME=smct
      - DB_PASSWORD=smct

  nginx:
    image: nginx:alpine
    container_name: scanner_monitoring_nginx
    ports:
      - "1009:1009"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - scanner_monitoring

networks:
  scanner_monitoring:
    driver: bridge
