services:
  scanner-monitoring:
    build:
      context: ./
      dockerfile: Dockerfile
    image: scanner-monitoring
    container_name: scanner-monitoring
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/default.conf



    networks:
      - scanner-monitoring
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1
      DB_PORT: 3306
      DB_DATABASE: scanner_monitoring
      DB_USERNAME: smct
      DB_PASSWORD: smct


  scanner-monitoring-nginx:
    image: nginx:alpine
    container_name: scanner-monitoring-nginx
    restart: unless-stopped
    ports:
      - 1009:1009
    volumes:
      - ./docker-compose/nginx/default.conf:/etc/nginx/default.conf

      - ./:/var/www

    networks:
      - scanner-monitoring


networks:
  scanner-monitoring:
    driver: bridge
